### ISSUE TITLE
Niche Situation - Installing Bewcloud via Cosmos Cloud (Docker Compose)

### ISSUE THREAD

**Issue by keyxmakerx** [bewcloud/bewcloud#14]
**Issue:** Unable to perform `"docker compose run website bash -c "cd /app && make migrate-db"`
**Goal:** Installing Bewcloud via Docker Compose built into [Cosmos Cloud](https://cosmos-cloud.io/doc/7%20Cosmos-compose/). 
**Current Situation/Setup:** I've got it running, however I can only get to the login screen. I assume I can't login or sign up is due to the lack of migration?
![image](https://github.com/user-attachments/assets/87c904f8-59b7-409d-bdaa-75b3ba98607f)

**Error:** I can't run docker compose via CLI, was trying to see if there was another way to do the migration?
**Note**: _I can't open any ports, which is fine. The Bewcloud interface and Postgresql are on the same docker network. Cosmos Cloud will have a URL that connects directly to the docker, without the need of any ports being opened. All of that seems to work just fine, but i'm not sure if it's an issue that Cosmos Cloud handles all of the HTTPS portion like a reverse proxy would._ 

**Compose:**
```
services:
  bewcloud:
    image: ghcr.io/bewcloud/bewcloud:main
    restart: always
    mem_limit: '512m'
    user: 1000:1000
    env_file:
      - path: /mnt/user/appdata/bewcloud/.env
        required: true
    volumes:
      - /mnt/user/Drive:/app/data-files
      - /mnt/user/appdata/bewcloud/lib/:/app/lib/

  postgresql:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=censored
      - POSTGRES_DB=bewcloud
    restart: on-failure
    volumes:
      - bewcloud-db:/var/lib/postgresql/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: '512m'

volumes:
  bewcloud-db:
    driver: local
```

Any assistance would be greatly appreciated, but i understand this is a VERY niche setup.

**Comment by keyxmakerx** [comment]
My ENV File

```
PORT=8000
BASE_URL="http://localhost:8000"

POSTGRESQL_HOST="postgresql"
POSTGRESQL_USER="postgres"
POSTGRESQL_PASSWORD="censored"
POSTGRESQL_DBNAME="bewcloud"
POSTGRESQL_PORT=5432
POSTGRESQL_CAFILE=""

JWT_SECRET="fake"
PASSWORD_SALT="fake"

BREVO_API_KEY="fake"

CONFIG_ALLOW_SIGNUPS="true"
CONFIG_ENABLED_APPS="news,notes,photos" # dashboard and files cannot be disabled
CONFIG_FILES_ROOT_PATH="data-files"
CONFIG_ENABLE_EMAILS="false" # if true, email verification will be required for signups (using Brevo)
CONFIG_ENABLE_FOREVER_SIGNUP="true" # if true, all signups become active for 100 years
```

**Comment by BrunoBernardino** [comment]
@keyxmakerx I'm unfamiliar with Cosmos, but what you can do is tweak the `Dockerfile` file to automatically run the migration and your `docker-compose.yml` file because the error you're seeing is related to the PostgreSQL connection not working.

Let's start with the `docker-compose.yml`. You seem to have no `ports:` setup for `postgresql`, so you should add a `- 5432:5432` to the `ports:` section there, as your `.env` file sets `POSTGRESQL_PORT=5432`.

You can try hitting the login/signup page then. The error should resemble something like "table users doesn't exist" because the migration hasn't run.

If you get there, we can tweak the `Dockerfile` to run the migrations, adding `deno run --allow-all migrate-db.ts` to the setup script/commands, where it would become:

```Dockerfile
FROM denoland/deno:ubuntu-1.46.2

EXPOSE 8000

RUN apt-get update && apt-get install -y make

WORKDIR /app

# These steps will be re-run upon each file change in your working directory:
ADD . /app

RUN rm -fr node_modules _fresh 

# Build fresh
RUN deno task build

RUN chown -R deno:deno /app /deno-dir

# Prefer not to run as root.
USER deno

# Compile the main app so that it doesn't need to be compiled each startup/entry.
RUN deno cache --reload main.ts

# Run database migrations
RUN deno run --allow-all migrate-db.ts

CMD ["run", "--allow-all", "main.ts"]
```

NOTE That if you change the Dockerfile _before_ fixing the database connection issue, the docker container likely won't build as it fails on running `migrate-db.ts`.

Alright, let men know if this helps!

**Comment by keyxmakerx** [comment]
Well I'm officially stumped, I do apologize since i believe this is me not knowing/understanding docker. 

The file you mentioned is just null for me on the file system, however it obviously exists. 
I then tried to locate it in the /var/lib/docker/volumes in case it was mounted as a volume, but i can't find it there either. I've tried messing around with bindings to see if i could bind the /bewcloud/app/lib directory to a dedicated directory but then it says it's missing files. 

Unfortunately i'm missing something here, and hate to bother you but any help would be appreciated. 

Proof it exists;
```
root@systemname:/mnt/user/appdata/bewcloud/app/data-files# docker exec bewcloud find / -name database.ts
find: '/proc/tty/driver': Permission denied
find: '/root': Permission denied
find: '/sys/kernel/slab': Input/output error
find: '/var/cache/apt/archives/partial': Permission denied
find: '/var/cache/ldconfig': Permission denied
find: '/var/lib/apt/lists/partial': Permission denied
/app/lib/interfaces/database.ts
```

**Comment by BrunoBernardino** [comment]
I don't mind trying to help at all. What do you mean it's null? What happens when you do `cat /mnt/user/appdata/bewcloud/app/lib/interfaces/database.ts`, assuming you have the app/repo files at `/mnt/user/appdata/bewcloud/app`?

**Comment by keyxmakerx** [comment]
Sorry again for the delay!

So if i use the exact compose above, i get this error in the bewcloud website logs;
"2024-09-26 18:04:39
error: Module not found "file:///app/lib/types.ts".
2024-09-26 18:04:39
at file:///app/routes/_404.tsx:4:35"

if I do the following version;
```
services:
  bewcloud:
    image: ghcr.io/bewcloud/bewcloud:main
    restart: always
    mem_limit: '512m'
    user: 1000:1000
    env_file:
      - path: /mnt/user/appdata/bewcloud/.env
        required: true
    volumes:
      - /mnt/user/appdata/bewcloud:/app

  postgresql:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=owxlCEZ6W2QXfja5vu7FvCs6
      - POSTGRES_DB=bewcloud
    restart: on-failure
    volumes:
      - bewcloud-db:/var/lib/postgresql/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: '512m'

volumes:
  bewcloud-db:
    driver: local
```

I get just 
```
2024-09-26 18:07:05
error: Module not found "file:///app/main.ts".
2024-09-26 18:07:09
error: Module not found "file:///app/main.ts".```

Lastly if i do just;

```services:
  bewcloud:
    image: ghcr.io/bewcloud/bewcloud:main
    restart: always
    mem_limit: '512m'
    user: 1000:1000
    env_file:
      - path: /mnt/user/appdata/bewcloud/.env
        required: true
    volumes:
      - /mnt/user/Drive:/app/data-files

  postgresql:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=censored
      - POSTGRES_DB=bewcloud
    restart: on-failure
    volumes:
      - bewcloud-db:/var/lib/postgresql/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: '512m'

volumes:
  bewcloud-db:
    driver: local```

I get 
```
2024-09-26 18:11:19
Crons starting...
2024-09-26 18:11:19
Using snapshot found at /app/_fresh
2024-09-26 18:11:19
2024-09-26 18:11:19
[48;5;121m 🍋 Fresh ready
2024-09-26 18:11:19
Local: http://localhost:8000/
2024-09-26 18:11:19```

In all of these examples, i can not fine a single file from the docker. I can't remember what command i used, but one of the commands for docker i was looking at listed the binding/volume as null. 

I tried searching for a volumbe, but all i'm finding is the DB
```root@BlackOpal:/var/lib/docker/volumes# ls -la | grep bew
drwx-----x 1 root root    10 Sep 26 11:12 bewcloud-db/```

**Comment by BrunoBernardino** [comment]
Looking at the above, you should see something at `/mnt/user/Drive`, like `ls -l /mnt/user/Drive` should have the app's root there.

**Comment by keyxmakerx** [comment]
the only thing in it are custom folders.

```root@BlackOpal:/mnt/user/Drive# ls
backups/  echoxmakerx/```

**Comment by BrunoBernardino** [comment]
Ah, never mind, that would be the files which you upload to bewCloud. What about `ls /mnt/user/appdata/bewcloud/` ?

**Comment by keyxmakerx** [comment]
Nothing :/ 
Like it's really weird, there's obviously files _somewhere_ but i just can't figure out where...
```

root@BlackOpal:/mnt/user/appdata/bewcloud# ls
app/  data-files/  lib/
root@BlackOpal:/mnt/user/appdata/bewcloud# cd app/
root@BlackOpal:/mnt/user/appdata/bewcloud/app# ls
data-files/
root@BlackOpal:/mnt/user/appdata/bewcloud/app# cd data-files/
root@BlackOpal:/mnt/user/appdata/bewcloud/app/data-files# ls
root@BlackOpal:/mnt/user/appdata/bewcloud/app/data-files# 
```

**Comment by BrunoBernardino** [comment]
We'll figure it out! Can't the people at cosmos help, though? They'll likely _know_ whereas we're trying to _figure out_.

Have you tried `find`? Like `find -L / -type f -name deno.json`?

**Comment by keyxmakerx** [comment]
Well finally some good news, 

Basically put i was wrong. I could run the migration all along. Instead of doing it via compose, i built it in Cosmos Cloud, and then performed exec commands to get it all setup. Admittedly i did cheat and use AI some. 

My eventual compose looks like this;

```
version: '3'

services:
  bewcloud:
    image: ghcr.io/bewcloud/bewcloud:main
    container_name: bewcloud-bewcloud
    restart: always
    mem_limit: '512m'
    user: "1000:1000"
    env_file:
      - /mnt/user/appdata/bewcloud/.env
    environment:
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_USER=${POSTGRESQL_USER}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DBNAME=${POSTGRESQL_DBNAME}
      - POSTGRESQL_PORT=${POSTGRESQL_PORT}
    volumes:
      - /mnt/user/appdata/bewcloud/data-files:/app/data-files
      - /mnt/user/appdata/bewcloud/deno-dir:/deno-dir
    depends_on:
      - postgresql

  postgresql:
    image: postgres:15
    container_name: bewcloud-postgresql
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRESQL_USER}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRES_DB=${POSTGRESQL_DBNAME}
    volumes:
      - /mnt/user/appdata/bewcloud/postgresql-data:/var/lib/postgresql/data
    mem_limit: '512m'

volumes:
  postgresql-data:
    driver: local```
    
    I then had to use docker exec to pull the database file, edit it, cp'ed it back to the docker proper, 
```
docker cp /tmp/database.ts bewcloud-bewcloud:/app/lib/interfaces/database.tsbewcloud
docker cp /tmp/database.ts bewcloud-bewcloud:/app/lib/interfaces/database.ts```

Then rebooted container, and finally! I ran the exec command and it worked! 

```
docker exec bewcloud-bewcloud deno run --allow-all /app/migrate-db.ts
Running "001-base.pgsql"...
Success!
Running "002-news-app.pgsql"...
Success!```

Now. For the bad news. 
I was able to sign up, but

"An error occurred during route handling or page rendering."
is what i get if i try to login. 
```
2024-10-01 23:10:26
2024-10-01 23:10:26.246 UTC [73] ERROR: relation "bewcloud_migrations" does not exist at character 15
2024-10-01 23:10:26
2024-10-01 23:10:26.246 UTC [73] STATEMENT: SELECT * FROM "bewcloud_migrations" ORDER BY "name" ASC
```
