### ISSUE TITLE
Error when running migrate-db: 'password authentication failed for user "phoeniqz"'

### ISSUE THREAD

**Issue by zPhoeniqz** [bewcloud/bewcloud#21]
Hi,

I'm trying to setup bewcloud with Caddy in docker. Everything works so far.
However when running `docker compose run bewcloud bash -c "cd /app && make migrate-db"` I get following error:
```
WARN[0000] The "UID" variable is not set. Defaulting to a blank string. 
WARN[0000] The "GID" variable is not set. Defaulting to a blank string. 
deno run --allow-net --allow-read --allow-env migrate-db.ts
A new release of Deno is available: 1.46.3 → 2.0.0 Run `deno upgrade` to install it.
Running "002-news-app.pgsql"...
Failed!
PostgresError: password authentication failed for user "phoeniqz"
    at Connection.#authenticateWithSasl (https://deno.land/x/postgres@v0.19.2/connection/connection.ts:657:15)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async Connection.#authenticate (https://deno.land/x/postgres@v0.19.2/connection/connection.ts:550:33)
    at async Connection.#startup (https://deno.land/x/postgres@v0.19.2/connection/connection.ts:415:7)
    at async Connection.startup (https://deno.land/x/postgres@v0.19.2/connection/connection.ts:494:11)
    at async Client.connect (https://deno.land/x/postgres@v0.19.2/client.ts:233:7)
    at async Database.connectToPostgres (file:///app/lib/interfaces/database.ts:45:5)
    at async Database.query (file:///app/lib/interfaces/database.ts:66:7)
    at async runMigrations (file:///app/migrate-db.ts:70:7)
    at async file:///app/migrate-db.ts:86:1 {
  fields: {
    severity: "FATAL",
    code: "28P01",
    message: 'password authentication failed for user "phoeniqz"',
    file: "auth.c",
    line: "326",
    routine: "auth_failed"
  },
  query: undefined,
  name: "PostgresError"
}
Running "001-base.pgsql"...
Failed!
PostgresError: password authentication failed for user "phoeniqz"
    at Connection.#authenticateWithSasl (https://deno.land/x/postgres@v0.19.2/connection/connection.ts:657:15)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async Connection.#authenticate (https://deno.land/x/postgres@v0.19.2/connection/connection.ts:550:33)
    at async Connection.#startup (https://deno.land/x/postgres@v0.19.2/connection/connection.ts:415:7)
    at async Connection.startup (https://deno.land/x/postgres@v0.19.2/connection/connection.ts:494:11)
    at async Client.connect (https://deno.land/x/postgres@v0.19.2/client.ts:233:7)
    at async Database.connectToPostgres (file:///app/lib/interfaces/database.ts:45:5)
    at async Database.query (file:///app/lib/interfaces/database.ts:66:7)
    at async runMigrations (file:///app/migrate-db.ts:70:7)
    at async file:///app/migrate-db.ts:86:1 {
  fields: {
    severity: "FATAL",
    code: "28P01",
    message: 'password authentication failed for user "phoeniqz"',
    file: "auth.c",
    line: "326",
    routine: "auth_failed"
  },
  query: undefined,
  name: "PostgresError"
}
```
---
This is my `docker-compose.yml`:
```
networks:
  app_network:
    external: true

services:
  bewcloud:
    image: ghcr.io/bewcloud/bewcloud:main
    restart: always
    ports:
      - 127.0.0.1:8000:8000
    mem_limit: '512m'
    user: "${UID}:${GID}" # if you run into issues with permissions for the data-files volume below, see other options at https://stackoverflow.com/a/56904335
    env_file:
      - path: .env
        required: true
    volumes:
      - ./data-files:/app/data-files
    networks:
      - app_network

  postgresql:
    image: postgres:15
    environment:
      - POSTGRES_USER=phoeniqz
      - POSTGRES_PASSWORD=fake
      - POSTGRES_DB=bewcloud
    restart: on-failure
    volumes:
      - bewcloud-db:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: '512m'
    networks:
      - app_network

volumes:
  bewcloud-db:
    driver: local
```

and this is my `.env`:
```
PORT=8000
BASE_URL="http://localhost:8000"

POSTGRESQL_HOST="postgresql" # docker container name or external hostname/IP
POSTGRESQL_USER="phoeniqz"
POSTGRESQL_PASSWORD="fake"
POSTGRESQL_DBNAME="bewcloud"
POSTGRESQL_PORT=5432
POSTGRESQL_CAFILE=""

#JWT_SECRET="fake"
#PASSWORD_SALT="fake"

#BREVO_API_KEY="fake"

CONFIG_ALLOW_SIGNUPS="false"
CONFIG_ENABLED_APPS="news,notes,photos" # dashboard and files cannot be disabled
CONFIG_FILES_ROOT_PATH="data-files"
CONFIG_ENABLE_EMAILS="false" # if true, email verification will be required for signups (using Brevo)
CONFIG_ENABLE_FOREVER_SIGNUP="true" # if true, all signups become active for 100 years
```

---
Also, this the output of `docker logs <id-of-postgres-container>`:
```
2024-11-09 02:10:01.611 UTC [1] LOG:  database system is ready to accept connections
2024-11-09 02:10:10.003 UTC [34] FATAL:  password authentication failed for user "phoeniqz"
2024-11-09 02:10:10.003 UTC [34] DETAIL:  Connection matched pg_hba.conf line 100: "host all all all scram-sha-256"
2024-11-09 02:10:10.012 UTC [35] FATAL:  password authentication failed for user "phoeniqz"
2024-11-09 02:10:10.012 UTC [35] DETAIL:  Connection matched pg_hba.conf line 100: "host all all all scram-sha-256"
2024-11-09 02:10:10.026 UTC [36] FATAL:  password authentication failed for user "phoeniqz"
2024-11-09 02:10:10.026 UTC [36] DETAIL:  Connection matched pg_hba.conf line 100: "host all all all scram-sha-256"
2024-11-09 02:14:20.259 UTC [45] FATAL:  password authentication failed for user "phoeniqz"
2024-11-09 02:14:20.259 UTC [45] DETAIL:  Connection matched pg_hba.conf line 100: "host all all all scram-sha-256"
2024-11-09 02:14:20.269 UTC [46] FATAL:  password authentication failed for user "phoeniqz"
2024-11-09 02:14:20.269 UTC [46] DETAIL:  Connection matched pg_hba.conf line 100: "host all all all scram-sha-256"
2024-11-09 02:14:20.284 UTC [47] FATAL:  password authentication failed for user "phoeniqz"
2024-11-09 02:14:20.284 UTC [47] DETAIL:  Connection matched pg_hba.conf line 100: "host all all all scram-sha-256"
```
