### ISSUE TITLE
Bewcloud crashed during uploads that are larger than around 200MB

### ISSUE THREAD

**Issue by zPhoeniqz** [bewcloud/bewcloud#22]
Hi,

I'm running Bewcloud behing a Caddy reverse proxy and my Bewcloud instance seems to just... crash when uploading files over roundabout 200MB.

I first thought this was a problem with my Caddy config, so I spent yesterday trying to debug my Caddyfile, without success. This is because there is nothing in the bewcloud logs that shows an error during the upload process, just that it exited with code 0 and restarted. The only place where I can find somewhat of an error message is the Caddy logs.

Caddy logs (prettified):
```json
{
  "level": "error",
  "ts": 1731454485.5662684,
  "logger": "http.log.error",
  "msg": "EOF",
  "request": {
    "remote_addr": "<my-client-ip>:33992",
    "proto": "HTTP/2.0",
    "method": "POST",
    "host": "<my-domain>",
    "uri": "/api/files/upload",
    "headers": {
      "Accept-Language": [
        "en-US,en;q=0.5"
      ],
      "Dnt": [
        "1"
      ],
      "Te": [
        "trailers"
      ],
      "Accept": [
        "*/*"
      ],
      "Content-Type": [
        "multipart/form-data; boundary=---------------------------45794064328702201261469521902"
      ],
      "Origin": [
        "https://<my-domain>"
      ],
      "Sec-Gpc": [
        "1"
      ],
      "Cookie": [
        "bewcloud-app-<my-client-cookie>"
      ],
      "Sec-Fetch-Dest": [
        "empty"
      ],
      "User-Agent": [
        "Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0"
      ],
      "Accept-Encoding": [
        "gzip, deflate, br, zstd"
      ],
      "Content-Length": [
        "208380838"
      ],
      "Sec-Fetch-Site": [
        "same-origin"
      ],
      "Referer": [
        "https://<my-domain>/files"
      ],
      "Sec-Fetch-Mode": [
        "cors"
      ],
      "Priority": [
        "u=4"
      ]
    },
    "tls": {
      "resumed": true,
      "version": 772,
      "cipher_suite": 4865,
      "proto": "h2",
      "proto_mutual": true,
      "server_name": "<my-domain>"
    }
  },
  "duration": 20.470945947,
  "status": 502,
  "err_id": "heuu2nahx",
  "err_trace": "reverseproxy.statusError (reverseproxy.go:886)"
}
```

Bewcloud logs:
```
bewcloud-1    | Crons starting...
bewcloud-1    | Using snapshot found at /app/_fresh
bewcloud-1    | 
bewcloud-1    |  🍋 Fresh ready 
bewcloud-1    |     Local: http://localhost:8000/
bewcloud-1    | 
bewcloud-1    | 2024-11-12T23:34:15.743Z - [200] GET http://<my-domain>/files
bewcloud-1    | 2024-11-12T23:34:16.008Z - [200] GET http://<my-domain>/styles.css
bewcloud-1 exited with code 0
bewcloud-1    | Crons starting...
bewcloud-1    | Using snapshot found at /app/_fresh
bewcloud-1    | 
bewcloud-1    |  🍋 Fresh ready 
bewcloud-1    |     Local: http://localhost:8000/
bewcloud-1    | 
```

Docker compose config:
```yaml
networks:
  app_network:
    external: true

services:
  bewcloud:
    image: ghcr.io/bewcloud/bewcloud:main
    restart: always
    ports:
      - 8000:8000
    mem_limit: '512m'
    user: "${UID}:${GID}"
    env_file: .env
    volumes:
      - ./data-files:/app/data-files
    networks:
      - app_network

  postgresql:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=<my-password>
      - POSTGRES_DB=bewcloud
    restart: on-failure
    volumes:
      - bewcloud-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: '512m'
    networks:
      - app_network

volumes:
  bewcloud-db:
    driver: local
```

.env file:
```
PORT=8000
BASE_URL="http://<my-domain>"

POSTGRESQL_HOST="postgresql" # docker container name or external hostname/IP
POSTGRESQL_USER="postgres"
POSTGRESQL_PASSWORD="<my-password>"
POSTGRESQL_DBNAME="bewcloud"
POSTGRESQL_PORT=5432
POSTGRESQL_CAFILE=""

JWT_SECRET="<my-jwt-secret>"
PASSWORD_SALT="<my-password-salt>"

#BREVO_API_KEY="fake"

CONFIG_ALLOW_SIGNUPS="false"
CONFIG_ENABLED_APPS="news,notes,photos" # dashboard and files cannot be disabled
CONFIG_FILES_ROOT_PATH="data-files"
CONFIG_ENABLE_EMAILS="false" # if true, email verification will be required for signups (using Brevo)
CONFIG_ENABLE_FOREVER_SIGNUP="true" # if true, all signups become active for 100 years
```

Just ask if there is any other info that is relevant.
