### ISSUE TITLE
[Startup error] File exists (os error 17)

### ISSUE THREAD

**Issue by Bigceru** [bewcloud/bewcloud#30]
## Error Description
Hi everyone, 

I was trying to start the Docker Compose on my ARM device (Raspberry Pi 4), but I encountered the following error (no other logs are shown):

```
error: File exists (os error 17), symlink '../commander@4.1.1/node_modules/commander' -> '/app/node_modules/.deno/node_modules/commander'
make: *** [Makefile:20: migrate-db] Error 1
```
## My Configuration
Here is my `docker-compose.yml`:

```yaml
services:
  website:
    image: ghcr.io/bewcloud/bewcloud:main
    restart: on-failure
    ports:
      - 127.0.0.1:8000:8000
    mem_limit: '256m'
    user: '${UID}:${GID}'
    env_file:
      - path: .env
        required: true
    volumes:
      - /mnt/ExternalHDD/bewCloud:/app/data-files

  postgresql:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRESQL_USER}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRES_DB=${POSTGRESQL_DBNAME}
    restart: on-failure
    volumes:
      - bewcloud-db:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: '256m'

volumes:
  bewcloud-db:
    driver: local
```

And my `.env` file:

```env
PORT=8000
BASE_URL="http://localhost:8000"

UID=1000
GID=1000

POSTGRESQL_HOST="*****"
POSTGRESQL_USER="*****"
POSTGRESQL_PASSWORD="*****"
POSTGRESQL_DBNAME="*****"
POSTGRESQL_PORT=5432
POSTGRESQL_CAFILE=""

JWT_SECRET="fake"
PASSWORD_SALT="fake"

BREVO_API_KEY="fake"

CONFIG_ALLOW_SIGNUPS="true"
CONFIG_ENABLED_APPS="news,notes,photos"
CONFIG_FILES_ROOT_PATH="data-files"
CONFIG_ENABLE_EMAILS="false"
CONFIG_ENABLE_FOREVER_SIGNUP="true"
```

## Steps to Reproduce
1. Run `docker compose run website bash -c "cd /app && make migrate-db"` on an ARM device with the configuration above.
2. Observe the error during the startup of the `website` service.

Thank you in advance for your help!
