### ISSUE TITLE
Can't get past login screen

### ISSUE THREAD

**Issue by F-4Dev** [bewcloud/bewcloud#35]
![image](https://github.com/user-attachments/assets/b701076a-c484-4a77-ac08-754334485e0d)
![2024-12-29-170837_hyprshot](https://github.com/user-attachments/assets/7fd2a6b7-2c39-49dd-bfd7-0e6113e4d52c)

When I enter my just created user password and email nothing happens.
I use cloudflare to access the page. 
followed the [instructions](github.com/bewcloud/bewcloud) for docker. 
Tried restarting the service.
Avoiding reinstalling because I'm still new to this and i don't exactly know how to cleanly remove the service.
Tank you for your help ^^

Terminal output:
![image](https://github.com/user-attachments/assets/52da5bfa-8f45-477a-ad1d-d1f37c52f705)

my docker-compose.yml:
```yml
services:
  website:
    image: ghcr.io/bewcloud/bewcloud:main
    restart: always
    ports:
      - 127.0.0.1:8000:8000
    mem_limit: '256m'
    user: '${UID}:${GID}' # if you run into issues with permissions for the data-files volume below, see other options at https://stackoverflow.com/a/56904335
    env_file:
      - path: .env
        required: true
    volumes:
      - /mnt/remaining/bewcloud/data-files:/app/data-files

  postgresql:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=fake
      - POSTGRES_DB=bewcloud
    restart: on-failure
    volumes:
      - /mnt/remaining/bewcloud/bewcloud-db:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: '256m'

volumes:
  bewcloud-db:
    driver: local
```
