### ISSUE TITLE
Trying to view photos crashes the server

### ISSUE THREAD

**Issue by sergi0g** [bewcloud/bewcloud#37]
Hello @BrunoBernardino! First of all, good job! This project looks very promising and I've been looking for a nextcloud alternative for a long time. This might be the one :wink:. I also have a few ideas to improve it. (If I can get it running, maybe you'll receive a PR as a gift)

# Issue description
When navigating to `/photos`, when bewcloud receives a request for an image, it crashes.

# Expected behavior
Photos load properly without crashing the server.

# Configuration
Docker compose (this is a template and I have verified that everything in `${}` is filled in):
```yaml
services:
  bewcloud-website:
    image: ghcr.io/bewcloud/bewcloud:v1.4.7
    entrypoint: bash
    command: -c "make migrate-db && deno run --allow-all main.ts"
    restart: unless-stopped
    ports:
      - 8053:8053
    mem_limit: "256m"
    environment:
      - PORT=8053
      - POSTGRESQL_HOST=bewcloud-db
      - POSTGRESQL_USER=bewcloud
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_DBNAME=bewcloud
      - POSTGRESQL_PORT=5432
      - JWT_SECRET=${JWT_SECRET}
      - PASSWORD_SALT=${PASSWORD_SALT}
      - BREVO_API_KEY=${BREVO_API_KEY}
      - CONFIG_ALLOW_SIGNUPS=${ALLOW_SIGNUPS}
      - CONFIG_ENABLED_APPS=news,notes,photos
      - CONFIG_FILES_ROOT_PATH=files
      - CONFIG_ENABLE_EMAILS=${ENABLE_EMAIL}
    volumes:
      - ${APP_DATA_DIR}/data/bewcloud/files:/files

  bewcloud-db:
    image: postgres:15-alpine
    container_name: bewcloud-db
    environment:
      - POSTGRES_USER=bewcloud
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=bewcloud
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/bewcloud/db:/var/lib/postgresql/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: "256m"
```
    
# Other notes
Everything else works just fine.
There is no error message or anything in the logs when it crashes. I can just tell that it has restarted.
```
(normal logs)
...
2025-01-09T16:46:08.473Z - [200] GET http://localhost:8053/photos
2025-01-09T16:46:08.812Z - [304] GET http://localhost:8053/styles.css
deno run --allow-net --allow-read --allow-env migrate-db.ts
No migrations to run!
Crons starting...
Using snapshot found at /app/_fresh

 🍋 Fresh ready
    Local: http://localhost:8053/
```

Do you have any idea what may have gone wrong?
