### ISSUE TITLE
Bewcloud isn't working behind a reverse proxy

### ISSUE THREAD

**Issue by badraxas** [bewcloud/bewcloud#43]
Hello,

I’m currently trying to set up Bewcloud, but I’m running into some issues. Although I was able to create my account, I now get a 303 error every time I try to log in. I’ve already checked the existing discussions about this error. I’m using HTTPS and I’ve updated the BASE_URL environment variable as recommended.

I run Bewcloud behind a Cloudflare tunnel and Nginx Proxy Manager via Docker Compose. Below, you’ll find my Docker Compose files for both Bewcloud and the Cloudflare/Nginx Proxy Manager setup. I’ve also included a screenshot of my Nginx Proxy Manager settings. I tried forwarding requests via HTTPS, but the interface doesn’t load.

```yaml
services:
  bewcloud:
    container_name: bewcloud
    image: ghcr.io/bewcloud/bewcloud:main
    restart: always
    environment:
      - PORT=8000
      - BASE_URL="https://domain.com"
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_USER=bewcloud
      - POSTGRESQL_PASSWORD=<password>
      - POSTGRESQL_DBNAME=bewcloud
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_CAFILE=
      - JWT_SECRET=fake
      - PASSWORD_SALT=fake
      - BREVO_API_KEY=fake
      - CONFIG_ALLOW_SIGNUPS=false
      - CONFIG_ENABLED_APPS=
      - CONFIG_FILES_ROOT_PATH=data-files
      - CONFIG_ENABLE_EMAILS=false
      - CONFIG_ENABLE_FOREVER_SIGNUP=true
    volumes:
      - ${DATA_PATH}:/app/data-files
    networks:
      - bewcloud_internal
      - gaia_shared

  postgresql:
    image: postgres:15
    environment:
      - POSTGRES_USER=bewcloud
      - POSTGRES_PASSWORD=<password>
      - POSTGRES_DB=bewcloud
    restart: on-failure
    volumes:
      - bewcloud-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: '256m'
    networks:
      - bewcloud_internal


volumes:
  bewcloud-db:
    driver: local

networks:
  gaia_shared:
    external: true
  bewcloud_internal:
    driver: bridge
```

my compose with cloudflared and nginx-proxy-manager : 
```yaml
version: '3'
services:
  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=<token>
    networks:
      - gaia_shared

  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ${CONFIG_PATH}/webserver/data:/data
      - ${CONFIG_PATH}/webserver/letsencrypt:/etc/letsencrypt
    networks:
      - gaia_shared

networks:
  gaia_shared:
    external: true
```

Below is my configuration in Nginx Proxy Manager. I also tried forwarding requests via HTTPS, but the interface still wouldn’t load.
<img width="500" alt="Image" src="https://github.com/user-attachments/assets/5b4abc30-9242-42fa-9cb9-e58e004d14e8" />
