### ISSUE TITLE
Ready to run docker container

### ISSUE THREAD

**Issue by Joly0** [bewcloud/bewcloud#5]
Hey, i wanted to try bewcloud, but as i cant use make commands etc on my main server, i wanted to give the docker container a try. So i built a container for myself https://hub.docker.com/r/joly0/bewcloud and tried to run it together with a postgres 15 docker container.

So far the container is working and the webui is accessible, though when i try to signup i get this error message:
![grafik](https://github.com/bewcloud/bewcloud/assets/13993216/5201d925-f035-4195-813e-5f560ca87a06)

Could it be, because i access the webui through http? I havent setup any ssl reverse proxy stuff for it, just wanted to give it a quick try.

Other than that, i think it would be a great idea, if there was a ready to run docker container for this, so the docker compose would be complete aswell. If any assistance is needed, i might be able to assist or provide a dockerfile for it

**Comment by BrunoBernardino** [comment]
Thanks! I'll address this with #1 as the demo would just deploy the same container, and act as a test, so I'll close this once we can figure out what's up with your setup.

Here's a  `docker-compose.yml` I'm using with this repo which has a `caddy` reverse proxy in front of it for TLS, but should work even without it:

```yaml
services:
  website:
    build: .
    restart: always
    ports:
      - 127.0.0.1:8000:8000
    mem_limit: '256m'
    volumes:
      - ./data-files:/app/data-files

  postgresql:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=fake
      - POSTGRES_DB=bewcloud
    restart: on-failure
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: '256m'

```

In any case, the error seems related to the postgres connection. 

Does your `.env` file have `POSTGRESQL_CAFILE=""`? That would disable TLS for PostgreSQL.
