### ISSUE TITLE
Not Able To Create User

### ISSUE THREAD

**Issue by imlezz** [bewcloud/bewcloud#51]
Hi there,

I am trying to test your app(since I am tired of Owncloud and Nextcloud as yourself) using docker compose and env file and running into some serious issues when it comes to creating the first admin account. My setup is as follows.

1. Running Ubuntu 22.04 on a LXC container.
2. Docker and Docker compose is installed on the container.
3. Downloaded docker-compose and .env file from your Github link.

My docker-compose config is as follows-

```
services:
  website:
    image: ghcr.io/bewcloud/bewcloud:main
    container_name: bewcloud
    restart: always
    ports:
      - 8000:8000
#    mem_limit: '4g'
    env_file:
      - path: .env
        required: true
    volumes:
      - ./data-files:/app/data-files

  postgresql:
    image: postgres:15
    container_name: postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test123
      - POSTGRES_DB=bewcloud
    restart: on-failure
    volumes:
      - ./bewcloud-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    mem_limit: '4g'

volumes:
  bewcloud-db:
    driver: local
```

My .env config is as follows-

```
PORT=8000
BASE_URL="http://10.0.80.8:8000"

POSTGRESQL_HOST="postgresql" # docker container name or external hostname/IP
POSTGRESQL_USER="postgres"
POSTGRESQL_PASSWORD="test123"
POSTGRESQL_DBNAME="bewcloud"
POSTGRESQL_PORT=5432
POSTGRESQL_CAFILE=""

JWT_SECRET="random_characters"
PASSWORD_SALT="random_characters"

#BREVO_API_KEY="fake"

CONFIG_ALLOW_SIGNUPS="false"
CONFIG_ENABLED_APPS="news,notes,photos,expenses" # dashboard and files cannot be disabled
CONFIG_FILES_ROOT_PATH="data-files"
CONFIG_ENABLE_EMAILS="false" # if true, email verification will be required for signups (using Brevo)
CONFIG_ENABLE_FOREVER_SIGNUP="true" # if true, all signups become active for 100 years
# CONFIG_ALLOWED_COOKIE_DOMAINS="example.com,example.net" # can be set to allow more than the BASE_URL's domain for session cookies
# CONFIG_SKIP_COOKIE_DOMAIN_SECURITY="true" # if true, the cookie domain will not be strictly set and checked against. This skipping slightly reduces security, but is usually necessary for reverse proxies like Cloudflare Tunnel.
```
The LXC container where I am deploying this has an ip address of 10.0.80.8 hence I have updated this under the BASE_URL section. Also, the mem_limit in the docker compose is commented because I get an error for the postgres when I have this value enabled during deployment. After I deploy the docker container and visit the portal using the URL http://10.0.80.8:8000, it pull the welcome screen and asks me to login or signup, I click on signup and enter my email and password and click signup button. I immediately get an error stating "Failed to signup! PostgresError: relation "bewcloud_users" does not exist"(screenshot attached below)

![Image](https://github.com/user-attachments/assets/0a3fb3b4-b191-4c3d-a4f7-c400e9cd22c2)

I have tried multiple things such as the following but none helped-

1. Changing the ports in the docker compose file.
2. Commenting the value container_name in the docker compose file.
3. Tried different password than the default ones.
4. Changed the image from image: ghcr.io/bewcloud/bewcloud:main to image: ghcr.io/bewcloud/bewcloud:latest in the docker compose file.
5. Using the default deocker-compose and .env file as is from your Github without making changes.
6. Manually added the bewcloud_users entry to the database by using the following command-```
CREATE TABLE bewcloud_users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    is_admin BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
```
And few other tweaks but none worked. I do not think it should be that difficult to create a new admin account after the container is deployed. I am currently running out of options and would need some help in getting this fixed. I think I might be doing something stupid and landing myself in such a situation.

Any help would be appreciated.

Cheers!
