### ISSUE TITLE
[Feature Request] Public File Sharing

### ISSUE THREAD

**Issue by BrunoBernardino** [bewcloud/bewcloud#57]
I frequently get requests via email to bring this functionality back and finish it up. I'm creating this issue to gauge interest.

This would be public file sharing (read) with and without password, not sharing between users or with write/delete permissions.

**Comment by Duckfromearth** [comment]
Please add this!! Very few competing apps have the functionality.

**Comment by BrunoBernardino** [comment]
Yes, that's the plan @TuxEnthusiast !

**Comment by BrunoBernardino** [comment]
@PontusTideman I'm talking about generating links (URLs) for specific files which can be shared _anywhere_. I'm not sure what you mean by sharing files instead of links, as you need links for people to be able to download the files.

**Comment by BrunoBernardino** [comment]
This has been released in [v2.2.0](https://github.com/bewcloud/bewcloud/releases/tag/v2.2.0)

**Comment by valerahime** [comment]
Thanks for adding this! It was the one thing I still needed from Nextcloud, so hopefully I can switch over in the near future.

I'm testing out the share functionality, but it's not currently working for me. I keep getting a `400` error when I try to make a link, both with and without a password. It's entirely possible this is a config error on my end, though.

Here's the console error (with my instance URL redacted):

```text
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data island-files_fileswrapper.js:1:15047
    me [bewCloud URL]/_frsh/js/cb41bf340d3e2db126c3316d1126feb658f17607/island-files_fileswrapper.js:1
    onClick [bewCloud URL]/_frsh/js/cb41bf340d3e2db126c3316d1126feb658f17607/island-files_fileswrapper.js:1
    Q [bewCloud URL]/_frsh/js/cb41bf340d3e2db126c3316d1126feb658f17607/chunk-USKNRMNM.js:1
    (Async: EventListener.handleEvent)
    M [bewCloud URL]/_frsh/js/cb41bf340d3e2db126c3316d1126feb658f17607/chunk-USKNRMNM.js:1
    pn [bewCloud URL]/_frsh/js/cb41bf340d3e2db126c3316d1126feb658f17607/chunk-USKNRMNM.js:1
    j [bewCloud URL]/_frsh/js/cb41bf340d3e2db126c3316d1126feb658f17607/chunk-USKNRMNM.js:1
    en [bewCloud URL]/_frsh/js/cb41bf340d3e2db126c3316d1126feb658f17607/chunk-USKNRMNM.js:1
    pn [bewCloud URL]/_frsh/js/cb41bf340d3e2db126c3316d1126feb658f17607/chunk-USKNRMNM.js:1
    j [bewCloud URL]/_frsh/js/cb41bf340d3e2db126c3316d1126feb658f17607/chunk-USKNRMNM.js:1
    en [bewCloud URL]/_frsh/js/cb41bf340d3e2db126c3316d1126feb658f17607/chunk-USKNRMNM.js:1
    pn [bewCloud URL]/_frsh/js/cb41bf340d3e2db126c3316d1126feb658f17607/chunk-USKNRMNM.js:1
    j [bewCloud URL]/_frsh/js/cb41bf340d3e2db126c3316d1126feb658f17607/chunk-USKNRMNM.js:1
    en [bewCloud URL]/_frsh/js/cb41bf340d3e2db126c3316d1126feb658f17607/chunk-USKNRMNM.js:1
    j [bewCloud URL]/_frsh/js/cb41bf340d3e2db126c3316d1126feb658f17607/chunk-USKNRMNM.js:1
    en [bewCloud URL]/_frsh/js/cb41bf340d3e2db126c3316d1126feb658f17607/chunk-USKNRMNM.js:1
    j [bewCloud URL]/_frsh/js/cb41bf340d3e2db126c3316d1126feb658f17607/chunk-USKNRMNM.js:1
    en [bewCloud URL]/_frsh/js/cb41bf340d3e2db126c3316d1126feb658f17607/chunk-USKNRMNM.js:1
    j [bewCloud URL]/_frsh/js/cb41bf340d3e2db126c3316d1126feb658f17607/chunk-USKNRMNM.js:1
    en [bewCloud URL]/_frsh/js/cb41bf340d3e2db126c3316d1126feb658f17607/chunk-USKNRMNM.js:1
    j [bewCloud URL]/_frsh/js/cb41bf340d3e2db126c3316d1126feb658f17607/chunk-USKNRMNM.js:1
    dn [bewCloud URL]/_frsh/js/cb41bf340d3e2db126c3316d1126feb658f17607/chunk-USKNRMNM.js:1
    s [bewCloud URL]/_frsh/js/cb41bf340d3e2db126c3316d1126feb658f17607/main.js:1
    (Async: setTimeout handler)
    Me [bewCloud URL]/_frsh/js/cb41bf340d3e2db126c3316d1126feb658f17607/main.js:1
    <anonymous> [bewCloud URL]/files:1
```

**Comment by BrunoBernardino** [comment]
@valerahime can you share your `bewcloud.config.ts` file? If you'd like to take this privately, you can email me at help@bewcloud.com.

**Comment by valerahime** [comment]
@BrunoBernardino Sure, I'll just redact part of it.

```ts
import { Config, PartialDeep } from './lib/types.ts';

/** Check the Config type for all the possible options and instructions. */
const config: PartialDeep<Config> = {
  auth: {
    baseUrl: 'https://[REDACTED]', // The base URL of the application you use to access the app, i.e. "http://localhost:8000" or "https://cloud.example.com" (SSO redirect, if enabled, will be this + /oidc/callback, so "https://cloud.example.com/oidc/callback")
    allowSignups: false, // If true, anyone can sign up for an account. Note that it's always possible to sign up for the first user, and they will be an admin
    enableEmailVerification: true, // If true, email verification will be required for signups (using SMTP settings below)
    enableForeverSignup: true, // If true, all signups become active for 100 years
    enableMultiFactor: true, // If true, users can enable multi-factor authentication (TOTP, Passkeys, or Email if the SMTP settings below are set)
    // allowedCookieDomains: ['example.com', 'example.net'], // Can be set to allow more than the baseUrl's domain for session cookies
    // skipCookieDomainSecurity: true, // If true, the cookie domain will not be strictly set and checked against. This skipping slightly reduces security, but is usually necessary for reverse proxies like Cloudflare Tunnel
  },
  files: {
    rootPath: 'data-files',
    allowPublicSharing: true, // If true, public file sharing will be allowed (still requires a user to enable sharing for a given file or directory)
  },
  core: {
    enabledApps: ['notes', 'photos'], // dashboard and files cannot be disabled
  },
  visuals: {
    title: "Valera's bewCloud",
    description: 'A personal bewCloud instance.',
    helpEmail: '[REDACTED]',
  },
  email: {
    from: '[REDACTED]',
    host: '[REDACTED]',
    port: [REDACTED],
  },
};
```

**Comment by BrunoBernardino** [comment]
That looks perfectly fine. I'm assuming you ran `make migrate-db` or the equivalent command, right?

I don't see how [any of the `JSON.parse() in the codebase`](https://github.com/search?q=repo%3Abewcloud%2Fbewcloud%20JSON.parse&type=code) could be causing an issue, there.

Can you paste (perhaps in a gist) the contents of `/_frsh/js/cb41bf340d3e2db126c3316d1126feb658f17607/island-files_fileswrapper.js` so I can try to see where the error is coming from?

**Comment by BrunoBernardino** [comment]
Thanks @valerahime ! I see the error is being reported here:

https://github.com/bewcloud/bewcloud/blob/7fac7febcfeabd542164f6af7c9402f5e46a0172/components/files/MainFiles.tsx#L552C7-L552C28

Which, given the error above, I believe originates here:

https://github.com/bewcloud/bewcloud/blob/7fac7febcfeabd542164f6af7c9402f5e46a0172/components/files/MainFiles.tsx#L535-L539

That means something is failing in that API call, where it's not returning JSON. Can you inspect the browser's Network tab and see what's being sent and what's the response?

**Comment by valerahime** [comment]
Of course. The response is, simply, `Bad Request`. However, I do see something interesting in the request:

```json
{"pathInView":"/","filePath":"\\console-export-2025-6-20_10-15-42.txt","password":""}
```

Maybe the double slashes in `filePath` is tripping it up? Seems to be happening across every file/folder I try. My base URL doesn't end in a slash, so I'm not sure where the second one is coming from.

**Comment by valerahime** [comment]
It's actually a Docker container on a Linux server. Used the This file was uploaded through the web UI. Here's the compose file (the `npm` network is for Nginx Proxy Manager):

```yml
services:
  bewcloud:
    image: ghcr.io/bewcloud/bewcloud:main
    container_name: bewcloud
    restart: unless-stopped
    ports: []
    networks:
      - bewcloud
      - npm
    env_file:
      - path: .env
        required: true
    depends_on:
      - postgres
    mem_limit: 256m
    volumes:
      - ./data-files:/app/data-files
      - ./bewcloud.config.ts:/app/bewcloud.config.ts
  postgres:
    image: postgres:17.5-alpine
    container_name: bewcloud-db
    restart: unless-stopped
    ports: []
    networks:
      - bewcloud
    environment:
      - POSTGRES_USER=$POSTGRESQL_USER
      - POSTGRES_PASSWORD=$POSTGRESQL_PASSWORD
      - POSTGRES_DB=$POSTGRESQL_DBNAME
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 256m
    volumes:
      - database:/var/lib/postgresql/data
volumes:
  database: null
networks:
  bewcloud: {}
  npm:
    external: true
```
