### ISSUE TITLE
How to run using reverse proxy

### ISSUE THREAD

**Issue by putraeka** [bewcloud/bewcloud#8]
Hello,

I'm tried to setup bewcloud using provided `docker-compose.yml` and `.env.sample` but I dont map port because I'm using reverse proxy. My setup look like this.

```yaml
services:
  website:
    build: ghcr.io/bewcloud/bewcloud
    restart: always
    #ports:
      #- 127.0.0.1:8000:8000
    mem_limit: '256m'
    user: "${UID}:${GID}" # if you run into issues with permissions for the data-files volume below, see other options at https://stackoverflow.com/a/56904335
    env_file:
      - path: .env
        required: true
    volumes:
      - ./data-files:/app/data-files
     networks:
      - proxy

  postgresql:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=fake
      - POSTGRES_DB=bewcloud
    restart: on-failure
    volumes:
      - bewcloud-db:/var/lib/postgresql/data
    #ports:
      #- 127.0.0.1:5432:5432
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: '256m'
    networks:
      - proxy


volumes:
  bewcloud-db:
    driver: local

networks:
  proxy:
    external: true
```

When using `docker compose up` everything looks normal

but when I run `docker compose run website bash -c "cd /app && make migrate-db"`

I got these

```
deno run --allow-net --allow-read --allow-env migrate-db.ts
A new release of Deno is available: 1.42.4 → 1.43.1 Run `deno upgrade` to install it.
Running "001-base.pgsql"...
Failed!
Error: failed to lookup address information: Name or service not known
    at async Object.connect (ext:deno_net/01_net.js:587:55)
    at async Connection.#openConnection (https://deno.land/x/postgres@v0.19.2/connection/connection.ts:266:18)
    at async Connection.#startup (https://deno.land/x/postgres@v0.19.2/connection/connection.ts:342:7)
    at async Connection.startup (https://deno.land/x/postgres@v0.19.2/connection/connection.ts:494:11)
    at async Client.connect (https://deno.land/x/postgres@v0.19.2/client.ts:233:7)
    at async Database.connectToPostgres (file:///app/lib/interfaces/database.ts:45:5)
    at async Database.query (file:///app/lib/interfaces/database.ts:66:7)
    at async runMigrations (file:///app/migrate-db.ts:70:7)
    at async file:///app/migrate-db.ts:86:1
Running "002-news-app.pgsql"...
Failed!
Error: failed to lookup address information: Name or service not known
    at async Object.connect (ext:deno_net/01_net.js:587:55)
    at async Connection.#openConnection (https://deno.land/x/postgres@v0.19.2/connection/connection.ts:266:18)
    at async Connection.#startup (https://deno.land/x/postgres@v0.19.2/connection/connection.ts:342:7)
    at async Connection.startup (https://deno.land/x/postgres@v0.19.2/connection/connection.ts:494:11)
    at async Client.connect (https://deno.land/x/postgres@v0.19.2/client.ts:233:7)
    at async Database.connectToPostgres (file:///app/lib/interfaces/database.ts:45:5)
    at async Database.query (file:///app/lib/interfaces/database.ts:66:7)
    at async runMigrations (file:///app/migrate-db.ts:70:7)
    at async file:///app/migrate-db.ts:86:1
```

What settings need to be changed?
